const DATABASE_HOST = process.env.DATABASE_HOST || ''
const DATABASE_PORT = Number(process.env.DATABASE_PORT || '')
const DATABASE_USER = process.env.DATABASE_USER || ''
const DATABASE_PASSWORD = process.env.DATABASE_PASSWORD || ''
const DATABASE_NAME = process.env.DATABASE_NAME || ''

export {
  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_NAME,
}

export const env = {
  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_NAME,
}
